### PR TITLE
sweeping refactor of base structure

### PR DESCRIPTION
**Pull request by JaynewDee**
- Express back-end replaced with Nest template
- Awaiting confirmation of database tech, none yet instantiated
- Next.js front-end replaced with core React/Typescript template

### CODE REVIEW

**Review by sarahwylie — APPROVED** [review]
Why was the name of the project changed to Client in the client/package.json? Is this just to differentiate the front and back end package.json files?

Otherwise looks good - thanks for getting the initial structure rocking and keeping up the .gitignore file so we don't end up screwing up one another's code. I'm going to do a pull request today!

**Comment by JaynewDee** [comment]
> Why was the name of the project changed to Client in the client/package.json? Is this just to differentiate the front and back end package.json files?
> 
> 
> 
> Otherwise looks good - thanks for getting the initial structure rocking and keeping up the .gitignore file so we don't end up screwing up one another's code. I'm going to do a pull request today!

Hey!  Great question.  I actually just scrapped the entirety of the previous Client folder as it was a template based on Next.js, and I replaced it with a generated React template.  I didn't mess with the code much beyond trimming unnecessary bits of the boilerplate.  So any changes to the package.json compared to the previous should just be the difference between the two generated templates.
My amateur understanding is that our full-stack application will essentially contain two smaller apps: the react application on the front end / client, and the Nest application on the back end / server.  I believe that means that the app names in the client and server package.json files can be generic, while our application's final name will ultimately be included in the package.json at the root of the project.

**Comment by sarahwylie** [comment]
> > Why was the name of the project changed to Client in the client/package.json? Is this just to differentiate the front and back end package.json files?
> > Otherwise looks good - thanks for getting the initial structure rocking and keeping up the .gitignore file so we don't end up screwing up one another's code. I'm going to do a pull request today!
> 
> Hey! Great question. I actually just scrapped the entirety of the previous Client folder as it was a template based on Next.js, and I replaced it with a generated React template. I didn't mess with the code much beyond trimming unnecessary bits of the boilerplate. So any changes to the package.json compared to the previous should just be the difference between the two generated templates. My amateur understanding is that our full-stack application will essentially contain two smaller apps: the react application on the front end / client, and the Nest application on the back end / server. I believe that means that the app names in the client and server package.json files can be generic, while our application's final name will ultimately be included in the package.json at the root of the project.

Exactly what I thought, just wanted to be sure. Thanks!

**Comment by akelstrom** [comment]
Josh, this looks good! I am going to approve. For all future PR's (and this goes for the rest of the team), we want to merge into develop branch before we merge into main. This will be for testing purposes- to test out features before we merge to our production branch (main).

**Review by akelstrom — APPROVED** [review]

**Pull request merged**
